[workspace]
authors = ["Michael Akpabey <micakpabey@gmail.com>", "Robert Akinie"]
channels = ["conda-forge"]
name = "MetaMorph"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
run-MetaMorph = "python metamorph/main.py"
MetaMorph-Concurrent = "python metamorph/mainConcurrent.py"

[dependencies]
python = "3.13.*"
pandas = ">=2.3.2,<3"
numpy = ">=2.3.1,<3"
pydantic = ">=2.11.7,<3"
python-dotenv = ">=1.1.1,<2"
ipython = ">=9.4.0,<10"
langchain = ">=0.3.17,<0.4"
langchain-community = ">=0.3.16,<0.4"
langchain-experimental = ">=0.3.4,<0.4"
jinja2 = ">=3.1.6,<4"

[pypi-dependencies]
langgraph = ">=0.5,<0.6"
langchain = ">=0.3.17,<0.4"
langchain-openai = ">=0.3.28,<0.4"
langchain-groq = ">=0.3.6,<0.4"
langchain-experimental = ">=0.3.2,<0.4" 
aiosqlite = ">=0.20.0"
langgraph-checkpoint-sqlite = ">=2.0.11"

